### PR TITLE
Updated Neptune example

### PR DESCRIPTION
**Pull request by SiddhantSadangi**
Updated example to be compatible with the latest version of the Neptune Python API (`neptune>=1.0`)

### CODE REVIEW

**Comment by fjcasti1** [comment]
> Updated example to be compatible with the latest version of the Neptune Python API (`neptune>=1.0`)

Hi @SiddhantSadangi, thank you so much for updating our tutorial for the Neptune <> Arize integration. We use copybara to sync this public repo from our private monorepo. We will make this change in a different PR and tag you. Thank you again!

**Comment by SiddhantSadangi** [comment]
Hey @fjcasti1 ,
Any ETA for this? :)

**Comment by fjcasti1** [comment]
Hey @SiddhantSadangi, sorry for the delay. I was on PTO and forgot to delegate it to someone. The update to this notebook was included in this [PR](https://github.com/Arize-ai/tutorials_python/pull/73). Thank you so much for your help. Let me know if there are any problems or if you have any feedback.

**Comment by SiddhantSadangi** [comment]
Thanks @fjcasti1 , looks perfect!

**Pull request closed without merging**
